/**
 * MSTM API
 * API for the \"Musikverein Sankt Mang\" website.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlogEntry { 
    testProperty?: number;
}

